/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TerminalDndPathPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enableExplorerDnd: true,
  enableFinderDnd: true
};
var TerminalDndPathPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.draggedPath = null;
    this.dragCleanupTimer = null;
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TerminalDndSettingTab(this.app, this));
    this.registerDomEvent(document, "dragstart", (e) => {
      const target = e.target;
      const fileItem = target == null ? void 0 : target.closest(".nav-file-title, .nav-folder-title");
      if (fileItem && fileItem.dataset.path) {
        this.draggedPath = fileItem.dataset.path;
        if (this.dragCleanupTimer)
          clearTimeout(this.dragCleanupTimer);
        this.dragCleanupTimer = setTimeout(() => {
          this.draggedPath = null;
        }, 1e4);
      }
    }, true);
    this.registerDomEvent(document, "dragend", () => {
      this.draggedPath = null;
      document.querySelectorAll(".xterm.dnd-path-dragover").forEach((el) => {
        el.classList.remove("dnd-path-dragover");
      });
    }, true);
    this.registerDomEvent(document, "dragenter", (e) => {
      var _a, _b, _c, _d;
      const xtermEl = (_a = e.target) == null ? void 0 : _a.closest(".xterm");
      if (!xtermEl)
        return;
      const isExternalDrag = (_d = (_c = (_b = e.dataTransfer) == null ? void 0 : _b.types) == null ? void 0 : _c.includes("Files")) != null ? _d : false;
      if (isExternalDrag && this.settings.enableFinderDnd) {
        e.preventDefault();
        e.stopPropagation();
      }
      if (this.draggedPath && this.settings.enableExplorerDnd) {
        e.preventDefault();
        e.stopPropagation();
      }
    }, true);
    this.registerDomEvent(document, "dragover", (e) => {
      var _a, _b, _c, _d;
      const xtermEl = (_a = e.target) == null ? void 0 : _a.closest(".xterm");
      if (!xtermEl) {
        document.querySelectorAll(".xterm.dnd-path-dragover").forEach((el) => {
          el.classList.remove("dnd-path-dragover");
        });
        return;
      }
      const isExternalDrag = (_d = (_c = (_b = e.dataTransfer) == null ? void 0 : _b.types) == null ? void 0 : _c.includes("Files")) != null ? _d : false;
      if (isExternalDrag && this.settings.enableFinderDnd) {
        e.preventDefault();
        e.stopPropagation();
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "copy";
        xtermEl.classList.add("dnd-path-dragover");
        return;
      }
      if (this.draggedPath && this.settings.enableExplorerDnd) {
        e.preventDefault();
        e.stopPropagation();
        if (e.dataTransfer)
          e.dataTransfer.dropEffect = "copy";
        xtermEl.classList.add("dnd-path-dragover");
        return;
      }
    }, true);
    this.registerDomEvent(document, "drop", (e) => {
      var _a, _b, _c, _d, _e;
      const xtermEl = (_a = e.target) == null ? void 0 : _a.closest(".xterm");
      if (!xtermEl)
        return;
      const isExternalDrag = (_d = (_c = (_b = e.dataTransfer) == null ? void 0 : _b.types) == null ? void 0 : _c.includes("Files")) != null ? _d : false;
      if (isExternalDrag && this.settings.enableFinderDnd) {
        e.preventDefault();
        e.stopPropagation();
        const files = (_e = e.dataTransfer) == null ? void 0 : _e.files;
        if (files && files.length > 0) {
          const filePath = this.getFileAbsolutePath(files[0]);
          if (filePath) {
            const escapedPath = this.escapeShellPath(filePath);
            this.pasteToTerminal(xtermEl, escapedPath);
          }
        }
        xtermEl.classList.remove("dnd-path-dragover");
        return;
      }
      if (this.draggedPath && this.settings.enableExplorerDnd) {
        e.preventDefault();
        e.stopPropagation();
        const escapedPath = this.escapeShellPath(this.draggedPath);
        this.pasteToTerminal(xtermEl, escapedPath);
        xtermEl.classList.remove("dnd-path-dragover");
        this.draggedPath = null;
        return;
      }
    }, true);
  }
  onunload() {
    if (this.dragCleanupTimer)
      clearTimeout(this.dragCleanupTimer);
    document.querySelectorAll(".xterm.dnd-path-dragover").forEach((el) => {
      el.classList.remove("dnd-path-dragover");
    });
  }
  pasteToTerminal(xtermEl, escapedPath) {
    try {
      const textarea = xtermEl.querySelector("textarea.xterm-helper-textarea");
      if (textarea) {
        const dt = new DataTransfer();
        dt.setData("text/plain", escapedPath);
        const clipboardEvent = new ClipboardEvent("paste", {
          clipboardData: dt,
          bubbles: true,
          cancelable: true
        });
        if (clipboardEvent.clipboardData && clipboardEvent.clipboardData.getData("text/plain") === escapedPath) {
          textarea.dispatchEvent(clipboardEvent);
        } else {
          throw new Error("ClipboardEvent data not passed");
        }
      } else {
        throw new Error("xterm textarea not found");
      }
    } catch (e) {
      navigator.clipboard.writeText(escapedPath).then(() => {
        new import_obsidian.Notice("Path copied to clipboard. Press Cmd+V to paste: " + escapedPath);
      }).catch(() => {
        new import_obsidian.Notice("Failed to copy path: " + escapedPath);
      });
    }
  }
  escapeShellPath(path) {
    if (!/[ '"()&|;<>!$`\\#~{}[\]*?]/.test(path))
      return path;
    return "'" + path.replace(/'/g, "'\\''") + "'";
  }
  getFileAbsolutePath(file) {
    try {
      const { webUtils } = require("electron");
      if (webUtils == null ? void 0 : webUtils.getPathForFile) {
        const path = webUtils.getPathForFile(file);
        if (path && path.length > 0)
          return path;
      }
    } catch (e) {
    }
    const legacyPath = file.path;
    if (legacyPath && typeof legacyPath === "string" && legacyPath.length > 0) {
      return legacyPath;
    }
    return void 0;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var TerminalDndSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Explorer drag & drop").setDesc("Drag files/folders from the Obsidian file explorer into the terminal to paste their path.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableExplorerDnd).onChange(async (value) => {
      this.plugin.settings.enableExplorerDnd = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Finder drag & drop").setDesc("Drag files/folders from Finder (or other file managers) into the terminal to paste their absolute path.").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableFinderDnd).onChange(async (value) => {
      this.plugin.settings.enableFinderDnd = value;
      await this.plugin.saveSettings();
    }));
  }
};
